environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
#

build_script:
  - gradlew isCI displayCommitHash buildPlugin --info
  - gradlew verifyPlugin --info
#

cache:
  - C:\Users\appveyor\.gradle

artifacts:
  - path: 'build\distributions\*.zip'
    name: intellij-dtlc
#
